version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4
  # For Testing on windows
  win: circleci/windows@2.4.0

workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: master
      - release-management/test-package:
          name: node-latest
          node_version: latest
          upload-coverage: true
      - release-management/test-package:
          name: node-12
      - release-management/test-package:
          node_version: '10'
          name: node-10
      - release-management/release-package:
          github-release: true
          post-job-steps:
            - release-management/merge
            - run: yarn ci-docs
          requires:
            - node-latest
            - node-12
            - node-10
          filters:
            branches:
              only: master
      - build-and-test-win:
        description: "Run tests on windows"
        executor: win/default
        steps:
          - checkout
          - restore_cache:
              keys:
                - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
                - v1-npm-{{checksum ".circleci/config.yml"}}
          - run:
              name: Install dependencies
              command: yarn
          - run:
              name: Build
              command: yarn build
          - save_cache:
              key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
              paths:
                - ~/node_modules
                - /usr/local/share/.cache/yarn
                - /usr/local/share/.config/yarn
          - verify-installed-plugin
          - run:
              name: Testing
              command: yarn test
