version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4

workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: master
      - release-management/test-package:
          name: node-latest
          node_version: latest
          upload-coverage: true
      - release-management/test-package:
          name: node-12
      - release-management/test-package:
          node_version: '10'
          name: node-10
      - release-management/test-package:
          os: 'windows'
          name: windows-test
      - release-management/release-package:
          github-release: true
          post-job-steps:
            - release-management/merge
            - run: yarn ci-docs
          requires:
            - node-latest
            - node-12
            - node-10
            - windows-test
          filters:
            branches:
              only: master
